In [3]:
import numpy as np;

In [4]:
#exact solution
a = np.reshape([-2.2,0.9,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0.9,-3.1,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,-2.2,0,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0,-3.1,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-3.1,0,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0,-3.1,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-3.1,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-3.1,0,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0,-3.1,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-4,0.9,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-3.1,0,0,0,0,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0,-2.2,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-3.1,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-3.1,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-3.1,0.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.9,0,0,0,0.9,-2.2],(25,25))
# print a
b = np.reshape([2,-10,1,-5,2,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,2,1,1,1,2],(25,1))
# print b
res = np.linalg.solve(a,b)
print np.reshape(res,(5,5))

[[ 4.51948839  8.72359135  4.54626916  5.65477528  1.69756493]
 [ 1.97471567  3.14150346  2.39211602  2.11921125  0.7170501 ]
 [ 0.25191769  0.87181455  0.82464287  0.65477528 -0.23582585]
 [-0.86770262 -0.34333271 -0.25362642 -0.45269118 -1.07300331]
 [-1.78622733 -1.27640865 -1.15584751 -1.34010637 -1.89627214]]


In [20]:
#policy evaluation approximation:

#functions
def transition(state,action,new_state):
    if state == 1:
        if new_state == 1:
            return 1.0
    elif state == 16:
        if new_state == 16:
            return 1.0
    elif action == 'n':
        if state in [2,3,4]:
            if new_state == state:
                return 1.0
        else:
            if new_state == state-4:
                return 1.0
    elif action == 'w': 
        if state in [5,9,13]:
            if state == new_state:
                return 1.0
        else:
            if new_state == state - 1:
                return 1.0
    elif action == 'e':
        if state in [4,8,12]:
            if new_state == state:
                return 1.0
        else:
            if new_state == state + 1:
                return 1.0
    elif action == 's':
        if state in [13,14,15]:
            if new_state == state:
                return 1.0
        else:
            if new_state == state + 4:
                return 1.0
    
    return 0.0

def reward(state,action,new_state):
    if state == 1 or state == 16:
        return 0.0
    else:
        return -1.0
        
y = 0.9
states = [x+1 for x in range(16)]
policy = [{'n': 0.25, 'e': 0.25, 's': 0.25, 'w': 0.25} for x in range(16)]
actions = ['n','e','s','w']

In [21]:
vals = list(np.zeros(16))
while True:
    # policy evaluation
    thresh = 0.0000001
    while True:
        delta = 0

        for state in states:
            new_val = 0
            for action in actions:
                for new_state in states:
                    new_val +=  policy[state-1][action] * transition(state,action,new_state) * (reward(state,action,new_state) + y * vals[new_state-1])
            delta = max([delta,(new_val - vals[state-1])])
            vals[state-1] = new_val

        print delta
        if delta < thresh:
            break;
    
    # policy improvement
    policy_stable = True
    for s in states:
        temp = max(policy[s-1].keys(), key=(lambda k: policy[s-1][k]))
        temp_vals = {'n': 0.0,'e': 0.0,'s': 0.0,'w': 0.0}
        old_val = 0
        for action in actions:
            for new_state in states:
                temp_vals[action] += transition(s,action,new_state) * (reward(s,action,new_state) + y * vals[new_state-1])
            if action == temp:
                old_val = temp_vals[action]
        new = max(temp_vals.keys(), key=(lambda k: temp_vals[k]))
        new_val = max(temp_vals.values())
        
        if new != temp and new_val > old_val:
            policy_stable = False
            policy[s-1] = {'n': 0.0,'e': 0.0,'s': 0.0,'w': 0.0}
            policy[s-1][new] = 1.0
    
    if policy_stable:
        break
    
print np.reshape(vals,(4,4))
opt_pol = [max(p.keys(), key=(lambda k: p[k])) for p in policy]
print np.reshape(opt_pol,(4,4))

0
0.75786328125
0
1.539
0.0644116383957
0.014492618639
0.00326083919378
0.000733688818601
0.000165079984185
3.71429964412e-05
8.35717419978e-06
1.88036419502e-06
4.23081943701e-07
9.51934371329e-08
[[ 0.         -1.         -1.9        -2.71      ]
 [-1.         -1.9        -2.71       -3.439     ]
 [-1.9        -2.71       -1.9        -2.84035487]
 [-2.71       -1.9        -1.          0.        ]]
[['s' 'w' 'w' 'w']
 ['n' 'w' 'n' 'n']
 ['n' 'w' 's' 's']
 ['n' 'e' 'e' 's']]


In [9]:
{'a':1,'b':2}.keys()

['a', 'b']